[package]
name = "cargon"
description = "Thin wrapper around the Argon2 C library"
license = "WTFPL"
authors = ["bryant <bryant@users.noreply.github.com>"]
version = "0.0.1"
repository = "https://github.com/FauxFaux/argon2min"
build = "build.rs"


[build-dependencies]
cc = "1"
